- hosts: all
  connection: local
  gather_facts: yes
  vars:
    k8s_cluster: gdcdevops-cluster
    k8s_zone: us-central1-a
    k8s_region: us-central1
    gcloud_project: gdcdevops
    node_count: 2
    destroy: True
  roles:
    - { role: create-k8s-cluster }