- hosts: all
  connection: local
  gather_facts: yes
  vars:
    k8s_cluster: gdcdevops-cluster
    k8s_zone: us-central1-a
    kubectl_version: v1.14.0
    gcloud_project: gdcdevops
    node_type: n1-standard-4
    disk_size: 40
    node_count: 2
    install_ingress_controller: True
    destroy: False
  roles:
    - { role: create-k8s-cluster }
    - { role: install-tools }