---
# tasks file for create-k8s-cluster
- name: Install software
  yum:
    name: [ "python2-pip", "jq" ]
    state: present
  become: yes

- name: Install pip prerequisites.
  pip:
    name: ['google-auth', 'requests']
  become: yes


- name: Copy Service Account file
  copy:
    src: "gcp-service-account.json"
    dest: "/tmp/service-account.json"
    mode: 0644

- name: Destroy Kubernetes Cluster if flag 'destroy' == True
  gcp_container_cluster:
      name: "{{ k8s_cluster }}"
      initial_node_count: "{{ node_count }}"
      zone: "{{ k8s_zone }}"
      project: "{{ gcloud_project }}"
      auth_kind: "serviceaccount"
      service_account_file: "/tmp/service-account.json"
      state: absent
  when: destroy == True

- name: Pause 120 seconds for cluster to release IP Address.
  pause:
    seconds: 120
  when: destroy == True

- name: delete external address
  gcp_compute_address:
    name: istio-gateway
    address: "{{ gateway_ip.stdout }}"
    region: "{{ k8s_region }}"
    project: "{{ gcloud_project }}"
    auth_kind: serviceaccount
    service_account_file: "/tmp/service-account.json"
    state: absent
  when: destroy == True
  ignore_errors: yes

- name: Ending playbook after destroying Kubernetes Cluster
  meta: end_play
  when: destroy == True

- name: Create Kubernetes Cluster
  gcp_container_cluster:
      name: "{{ k8s_cluster }}"
      initial_node_count: "{{ node_count }}"
      node_config:
        machine_type: "{{ node_type }}"
        disk_size_gb: "{{ disk_size }}"
      zone: "{{ k8s_zone }}"
      project: "{{ gcloud_project }}"
      auth_kind: "serviceaccount"
      service_account_file: "/tmp/service-account.json"
      state: present
